project:
  type: website

website:
  title: "Ty young"
  navbar:
    left:
      - href: index.html
        text: Home
      - about.html
      - href: Assignments.html
        text: Assignments

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

