project:
  type: website

website:
  title: "Ty young"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Assignments.qmd
        text: Assignments

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

